services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: farid
      MYSQL_DATABASE: farid
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql

